# Generated by Django 3.2.25 on 2024-12-09 15:27

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_fieldworkfile_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('media_type', models.CharField(choices=[('IMAGE', '图片'), ('AUDIO', '音频'), ('VIDEO', '视频'), ('DOCUMENT', '文档')], max_length=10, verbose_name='媒体类型')),
                ('category', models.CharField(choices=[('FOLKLORE', '风土人情'), ('INTERVIEW', '访谈记录'), ('LITERATURE', '文献资料')], max_length=10, verbose_name='资料分类')),
                ('file_path', models.FileField(upload_to='survey_files/%Y/%m/', verbose_name='文件路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='调查名称')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.RemoveField(
            model_name='fieldworkfile',
            name='project',
        ),
        migrations.RemoveField(
            model_name='fieldworkfile',
            name='status_changed_by',
        ),
        migrations.RemoveField(
            model_name='fieldworkfile',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='fieldworkproject',
            name='investigator',
        ),
        migrations.RemoveField(
            model_name='fieldworkproject',
            name='status_changed_by',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='file',
        ),
        migrations.RemoveField(
            model_name='like',
            name='project',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=11, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='FieldworkFile',
        ),
        migrations.DeleteModel(
            name='FieldworkProject',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AddField(
            model_name='survey',
            name='investigator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='调查人'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='myapp.survey', verbose_name='所属调查'),
        ),
    ]
